### ISSUE TITLE
Tag that seems not supported.

### ISSUE THREAD

**Issue by versemonger** [creatorrr/pyAIML#7]
The following example is not supported by pyAIML.

```
<category>
    <pattern>WHAT ABOUT MOVIES</pattern>
    <template>Do you like comedy movies</template>
</category>

<category>
    <pattern>YES</pattern>
    <that>Do you like comedy movies</that>
    <template>Nice, I like comedy movies too.</template>
</category>

<category>
    <pattern>NO</pattern>
    <that>Do you like comedy movies</that>
    <template>Ok! But I like comedy movies.</template>
</category>
```

**Comment by versemonger** [comment]
I later read self-test.aiml and found that pyAIML may has its own standard about how to use that. This this may not be a bug, but a lack of feature.

**Comment by datta90** [comment]
@versemonger 
write all letters in <that> tag in CAPTIAL LETTERS
for eg.
<that>Do you like comedy movies</that> should be
<that>DO YOU LIKE COMEDY MOVIES</that>

then it will work  fine 
i had faced same issues a  while ago
